// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cleverbit_tech_test.Entities.Database
{
    public partial class Employees
    {
        [Key]
        public int Id { get; set; }
        public int IdRegion { get; set; }
        [Required]
        [StringLength(255)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(255)]
        public string LastName { get; set; }

        [ForeignKey(nameof(IdRegion))]
        [InverseProperty(nameof(Regions.Employees))]
        public virtual Regions IdRegionNavigation { get; set; }
    }
}