// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cleverbit_tech_test.Entities.Database
{
    public partial class Regions
    {
        public Regions()
        {
            Employees = new HashSet<Employees>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        public int? IdParent { get; set; }

        [InverseProperty("IdRegionNavigation")]
        public virtual ICollection<Employees> Employees { get; set; }
    }
}